Joker limit
Badjeck/TRIVIAAAAAAA pull request #10
Opened 2023-04-07 12:25 UTC by MarieDugoua

2023-04-07 13:19 UTC, Lotfihihi commented
manque beaucoup de choses du master actuel

2023-04-13 08:24 UTC, Saiiga requested changes

2023-04-13 08:24 UTC, Saiiga commented on tests/game.test.ts
>  });
Add a test when joker is used

2023-04-13 08:24 UTC, Saiiga commented on src/playerPool.ts
> +    private _usedJoker: Array<boolean> = [];
Change the name to make it understable that was a list

2023-04-13 08:24 UTC, Saiiga commented on tests/game.test.ts
> +        game.useJoker();
can't work

2023-04-13 08:24 UTC, Saiiga commented on tests/game.test.ts
> +        game.useJoker();
verify : 
number of coin
if joker was used

2023-04-13 08:24 UTC, Saiiga commented on src/playerPool.ts
> +    public currentPlayerUseJoker(): void {
why ? not uselesss ?

2023-04-13 08:24 UTC, Saiiga commented on src/playerPool.ts
>      private _players: Array<string> = [];
rename to "playersName"

2023-04-13 08:24 UTC, Saiiga commented on src/playerPool.ts
>      private _currentPlayer: number = 0;
rename to currentPlayerIndex

2023-04-13 08:24 UTC, Saiiga commented on src/game-runner.ts
> +            game.useJoker();
Remove the hardcoded call

2023-04-13 08:24 UTC, Saiiga commented on src/game.ts
> +    private usedJoker: Array<boolean> = [];
Move this logic in PlayerPool

2023-04-20 09:34 UTC, Lotfihihi approved these changes
OK

2023-04-20 09:38 UTC, Saiiga approved these changes

2023-04-20 09:39 UTC, merged